[package]
name = "euclase"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
winit = "0.30.11"
anyhow = "1.0.98"
pollster = "0.4.0"
env_logger = "0.11.8"

euclase_vulkan = { path = "../euclase_vulkan" }
